# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: saffair CI

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Create backend env file
        run: |
          touch .env
          echo PORT=8080 >> .env  
          echo MONGO_ATLAS_URL='${{ secrets.MONGO_ATLAS_URL }}' >> .env
  
          cat .env

      - name: Create client env file
        run: |
          cd client 
          touch .env
          echo BASE_URL='https://dev.peersuma.studio/api/' >> .env

          cat .env

      - run: yarn install
      - run: cd client && yarn install && yarn build
     
      - run: pm2 reload all
